language: node_js
node_js:
  - "6"
addons:
  code_climate:
    repo_token: d25af2c5d3f707c294f0fec0876cb4c89e377e385cc239c5c2a0887af44adb0c
after_script:
  - codeclimate-test-reporter < coverage/lcov.info